version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - all

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - pdf

